### ISSUE TITLE
Project fails to load

### ISSUE THREAD

**Issue by relaxnow** [playframework/play-webgoat#168]
```
play-webgoat % sbt
[info] welcome to sbt 1.10.5 (Homebrew Java 23.0.1)
[info] loading settings for project play-webgoat-build from plugins.sbt,sbt-coursier-654738138923564774.sbt ...
[info] loading project definition from /play-webgoat/project
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.2.0 (early-semver) is selected over 1.0.6
[error] 	    +- org.playframework.twirl:twirl-api_2.12:2.0.7       (depends on 2.2.0)
[error] 	    +- com.github.sbt:sbt-native-packager:1.10.0 (scalaVersion=2.12, sbtVersion=1.0) (depends on 2.2.0)
[error] 	    +- io.get-coursier:coursier_2.12:1.0.3                (depends on 1.0.6)
[error] 
[error] 
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:90)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:142)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:144)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:131)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:220
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:169)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3888)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1575)
[error] (update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.2.0 (early-semver) is selected over 1.0.6
[error] 	    +- org.playframework.twirl:twirl-api_2.12:2.0.7       (depends on 2.2.0)
[error] 	    +- com.github.sbt:sbt-native-packager:1.10.0 (scalaVersion=2.12, sbtVersion=1.0) (depends on 2.2.0)
[error] 	    +- io.get-coursier:coursier_2.12:1.0.3                (depends on 1.0.6)
[error] 
[error] 
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

**Comment by relaxnow** [comment]
Sorry, my bad, a fresh clone does work I think I messed something up.
